version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kodilla-library-db
    restart: always
    environment:
      POSTGRES_DB: kodilla_library
      POSTGRES_USER: kodilla_user
      POSTGRES_PASSWORD: kodilla_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
